language: java
jdk: openjdk8
deploy:
  provider: releases
  file: "/home/travis/build/whyleee/liquibase-nochangeloglock/target/liquibase-nochangeloglock-1.2-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true